# Generated by Django 2.2 on 2019-04-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
