# Generated by Django 2.2 on 2019-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20190418_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
